spring:
  data:
    mongodb:
      uri: mongodb+srv://journaluser:n123456niki@cluster0.duscwgn.mongodb.net/journaluser?authSource=admin&retryWrites=true&w=majority
      database: journaluser
      auto-index-creation: true

server:
  port: 8081
  servlet:
    context-path: /journal

